#pragma once

#define LOOP_BOW_THRES 0.015
#define MATCH_INDEX_DIST 5
// #define MATCH_INDEX_DIST 1
#define FAST_THRES (20.0f)
#define ORB_FEATURE_SIZE (32) // For ORB
#define LOOP_FEATURE_NUM (1000)
// #define USE_CUDA

// #define MIN_MOVEMENT_KEYFRAME 0.1
#define MIN_MOVEMENT_KEYFRAME 0.4
#define MIN_KEYFEATURES 10